name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run application
        run: docker-compose up -d web

      - name: Run test suite
        run: docker-compose run -T --rm app pytest -v
        if: always()

      - name: Check Migrations are up-to-date
        run: docker-compose run -T --rm app ./manage.py makemigrations --check
        if: always()
